//
// Created by leonardo on 10/06/16.
//

#ifndef INC_1942OLDENAIT_DIMENSIONSUPERFICIES_HPP_H
#define INC_1942OLDENAIT_DIMENSIONSUPERFICIES_HPP_H

#define ANCHO_AVION_PEQUENIO_1 50
#define ALTO_AVION_PEQUENIO_1 18
#define ANCHO_AVION_PEQUENIO_2 15
#define ALTO_AVION_PEQUENIO_2 45
#define AVION_PEQUENIO_OFFSET_ANCHO 35
#define AVION_PEQUENIO_OFFSET_ALTO 24

#define ALTO_SUPERFICIE_DISPARO 36
#define ANCHO_SUPERFICIE_DISPARO 7

#endif //INC_1942OLDENAIT_DIMENSIONSUPERFICIES_HPP_H
