//
// Created by leonardo on 10/06/16.
//

#ifndef INC_1942OLDENAIT_DIMENSIONSUPERFICIES_HPP_H
#define INC_1942OLDENAIT_DIMENSIONSUPERFICIES_HPP_H

#define ANCHO_AVION_PEQUENIO_1 50
#define ALTO_AVION_PEQUENIO_1 18
#define ANCHO_AVION_PEQUENIO_2 15
#define ALTO_AVION_PEQUENIO_2 45
#define AVION_PEQUENIO_OFFSET_ANCHO 35
#define AVION_PEQUENIO_OFFSET_ALTO 24

//#define ALTO_SUPERFICIE_DISPARO 36
#define ALTO_SUPERFICIE_DISPARO 30
#define ANCHO_SUPERFICIE_DISPARO 7

#define AVION_ANCHO_1 30
#define AVION_ALTO_1 66
#define AVION_ANCHO_2 54
#define AVION_ALTO_2 32
#define OFFSET_AVION_ANCHO 14
#define OFFSET_AVION_ALTO 28

#define AVION_ENEMIGO_GRANDE_ANCHO_1 37
#define AVION_ENEMIGO_GRANDE_ALTO_1 125
#define AVION_ENEMIGO_GRANDE_ANCHO_2 88
#define AVION_ENEMIGO_GRANDE_ALTO_2 40
#define OFFSET_ANCHO_AVION_GRANDE 26

#define DISPARO_ENEMIGO_SUPERFICIE_ANCHO 10
#define DISPARO_ENEMIGO_SUPERFICIE_ALTO 10

#define AVION_ENEMIGO_MEDIANO_ANCHO_1 12
#define AVION_ENEMIGO_MEDIANO_ALTO_1 72
#define AVION_ENEMIGO_MEDIANO_ANCHO_2 22
#define AVION_ENEMIGO_MEDIANO_ALTO_2 23
#define OFFSET_ANCHO_AVION_MEDIANO 12
#define OFFSET_ALTO_AVION_MEDIANO 32
#define OFFSET_ANCHO_AVION_MEDIANO_2 33

#endif //INC_1942OLDENAIT_DIMENSIONSUPERFICIES_HPP_H
