#ifndef INC_1942OLDENAIT_DIMENSIONSUPERFICIES_HPP_H
#define INC_1942OLDENAIT_DIMENSIONSUPERFICIES_HPP_H

#define ANCHO_AVION_PEQUENIO_1 50
#define ALTO_AVION_PEQUENIO_1 10
#define ANCHO_AVION_PEQUENIO_2 20
#define ALTO_AVION_PEQUENIO_2 45
#define OFFSET_AVION_PEQUENIO_ALTO 35
#define AVION_PEQUENIO_OFFSET_ALTO_DEFAULT 10
#define AVION_PEQUENIO_OFFSET_ANCHO_DEFAULT 20

#define ALTO_SUPERFICIE_DISPARO 30
#define ANCHO_SUPERFICIE_DISPARO 7

#define AVION_ANCHO_1 30
#define AVION_ALTO_1 66
#define AVION_ANCHO_2 54
#define AVION_ALTO_2 32
#define OFFSET_AVION_ANCHO 14
#define OFFSET_AVION_ALTO 28
#define OFFSET_AVION_ANCHO_DEFAULT 11
#define OFFSET_AVION_ALTO_DEFAULT 6


#define AVION_ENEMIGO_GRANDE_ANCHO_1 48
#define AVION_ENEMIGO_GRANDE_ALTO_1 82
#define OFFSET_AVION_ENEMIGO_GRANDE_ALTO_1 45
#define OFFSET_AVION_ENEMIGO_GRANDE_ANCHO_1 18
#define AVION_ENEMIGO_GRANDE_ANCHO_2 80
#define AVION_ENEMIGO_GRANDE_ALTO_2 28
#define OFFSET_AVION_ENEMIGO_GRANDE_ALTO_2 100
#define AVION_ENEMIGO_GRANDE_ANCHO_3 28
#define AVION_ENEMIGO_GRANDE_ALTO_3 49
#define OFFSET_AVION_ENEMIGO_GRANDE_ANCHO_DEFAULT 5
#define OFFSET_AVION_ENEMIGO_GRANDE_ALTO_DEFAULT 5

#define DISPARO_ENEMIGO_SUPERFICIE_ANCHO 10
#define DISPARO_ENEMIGO_SUPERFICIE_ALTO 10

#define AVION_ENEMIGO_MEDIANO_ANCHO_1 25
#define AVION_ENEMIGO_MEDIANO_ALTO_1 40
#define OFFSET_AVION_ENEMIGO_MEDIANO_ANCHO_1 15
#define OFFSET_AVION_ENEMIGO_MEDIANO_ALTO_1 5
#define AVION_ENEMIGO_MEDIANO_ANCHO_2 55
#define AVION_ENEMIGO_MEDIANO_ALTO_2 6
#define OFFSET_AVION_ENEMIGO_ALTO_2 25
#define OFFSET_ALTO_AVION_MEDIANO_DEFAULT 15
#define OFFSET_ANCHO_AVION_MEDIANO_DEFAULT 6

#endif //INC_1942OLDENAIT_DIMENSIONSUPERFICIES_HPP_H
